Create README.md
RiartC/PrWR-Projektauftrag pull request #1
Opened 2024-12-05 10:38 UTC by RiartC

Ist das README so in Ordnung?

2024-12-05 10:44 UTC, Jacques-Mock-Schindler commented on README.md
> +Die Daten haben wir vom Datenkatalog | Kanton Zürich.
Hier bitte die URL angeben

2024-12-05 10:45 UTC, Jacques-Mock-Schindler commented on README.md
> +Visualisierungstypen: Stacked Area Chart, Choropleth Map, Bar Chart (horizontal & vertical), Line Graph
Woher kommen die Karten für die Choropleth Map -> hier bitte auch eine URL angeben

2024-12-05 10:45 UTC, Jacques-Mock-Schindler requested changes
Bearbeiten Sie meine Inlinekommentare

2024-12-20 20:14 UTC, RiartC commented
Wir haben das README verändert, sodass es Ihren Anforderungen entspricht

2024-12-20 20:14 UTC, merged